@startuml

title __ROBOT's Class Diagram__\n

  namespace com.stroganov {
    class com.stroganov.Candle {
    }
  }
  

  namespace com.stroganov {
    class com.stroganov.CandleStream {
    }
  }
  

  namespace com.stroganov {
    class com.stroganov.DateFromString {
    }
  }
  

  namespace com.stroganov {
    namespace Grafics {
      class com.stroganov.Grafics.GraphicOfBalance {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Grafics {
      class com.stroganov.Grafics.GraphicOfRSAIndicator {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Grafics {
      class com.stroganov.Grafics.GraphicOfTransactions {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Grafics {
      class com.stroganov.Grafics.Report {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Indicators {
      abstract class com.stroganov.Indicators.AbstractIndicator {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Indicators {
      class com.stroganov.Indicators.EMA {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Indicators {
      class com.stroganov.Indicators.RSA_Indicator {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Indicators {
      class com.stroganov.Indicators.RSA_Indicator2 {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Indicators {
      class com.stroganov.Indicators.SMA {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Indicators {
      class com.stroganov.Indicators.SMMA {
      }
    }
  }
  

  namespace com.stroganov {
    class com.stroganov.Main {
    }
  }
  

  namespace com.stroganov {
    namespace Strategies {
      abstract class com.stroganov.Strategies.AbstractRSA_Strategy {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Strategies {
      class com.stroganov.Strategies.Balance {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Strategies {
      class com.stroganov.Strategies.RSA_Strategy {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Strategies {
      class com.stroganov.Strategies.RSA_StrategyStopLoss {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Strategies {
      class com.stroganov.Strategies.TradeAction {
      }
    }
  }
  

  namespace com.stroganov {
    namespace Strategies {
      class com.stroganov.Strategies.Transaction {
      }
    }
  }
  

  com.stroganov.Grafics.Report o-- com.stroganov.Strategies.Balance : balance
  com.stroganov.Indicators.EMA -up-|> com.stroganov.Indicators.AbstractIndicator
  com.stroganov.Indicators.RSA_Indicator -up-|> com.stroganov.Indicators.AbstractIndicator
  com.stroganov.Indicators.RSA_Indicator2 -up-|> com.stroganov.Indicators.AbstractIndicator
  com.stroganov.Indicators.SMA -up-|> com.stroganov.Indicators.AbstractIndicator
  com.stroganov.Strategies.AbstractRSA_Strategy o-- com.stroganov.CandleStream : candleStream
  com.stroganov.Strategies.AbstractRSA_Strategy o-- com.stroganov.Indicators.AbstractIndicator : rsa
  com.stroganov.Strategies.AbstractRSA_Strategy o-- com.stroganov.Strategies.TradeAction : tradeAction
  com.stroganov.Strategies.RSA_Strategy o-- com.stroganov.CandleStream : candleStream
  com.stroganov.Strategies.RSA_Strategy o-- com.stroganov.Indicators.AbstractIndicator : rsa
  com.stroganov.Strategies.RSA_Strategy o-- com.stroganov.Strategies.TradeAction : tradeAction
  com.stroganov.Strategies.RSA_StrategyStopLoss -up-|> com.stroganov.Strategies.AbstractRSA_Strategy
  com.stroganov.Strategies.TradeAction o-- com.stroganov.Strategies.Balance : balance
  com.stroganov.Strategies.Transaction o-- com.stroganov.Strategies.Balance : balance


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
