@startuml

title __STRATEGIES's Class Diagram__\n

  namespace com.stroganov {
    namespace Strategies {
      abstract class com.stroganov.Strategies.AbstractRSA_Strategy {
          ~ paperCount : int
          ~ transactionArrayList : ArrayList<Transaction>
          + AbstractRSA_Strategy()
          + getTransactionArray()
          + printLn()
          {abstract} + startAbstractStrategy()
      }
    }
  }
  

  namespace com.stroganov {
    namespace Strategies {
      class com.stroganov.Strategies.Balance {
          - allBalance : Double
          - freeMoney : Double
          - papers : int
          + Balance()
          + Balance()
          + getAllBalance()
          + getAllBalance()
          + getFreeMoney()
          + getPapers()
          + setAllBalance()
          + setFreeMoney()
          + setPapers()
      }
    }
  }
  

  namespace com.stroganov {
    namespace Strategies {
      class com.stroganov.Strategies.RSA_Strategy {
          ~ paperCount : int
          ~ transactionArrayList : ArrayList<Transaction>
          + RSA_Strategy()
          + getTransactionArrayList()
          + printLn()
          + startStrategy()
      }
    }
  }
  

  namespace com.stroganov {
    namespace Strategies {
      class com.stroganov.Strategies.RSA_StrategyStopLoss {
          + RSA_StrategyStopLoss()
          + startAbstractStrategy()
      }
    }
  }
  

  namespace com.stroganov {
    namespace Strategies {
      class com.stroganov.Strategies.TradeAction {
          + TradeAction()
          + buy()
          + getBalance()
          + sell()
      }
    }
  }
  

  namespace com.stroganov {
    namespace Strategies {
      class com.stroganov.Strategies.Transaction {
          - candleIndex : int
          - countPapers : int
          - price : Double
          - tradeDirect : String
          + Transaction()
          + equals()
          + getBalance()
          + getCandleIndex()
          + getCountPapers()
          + getPrice()
          + getTradeDirect()
          + hashCode()
          + toString()
      }
    }
  }
  

  com.stroganov.Strategies.AbstractRSA_Strategy o-- com.stroganov.CandleStream : candleStream
  com.stroganov.Strategies.AbstractRSA_Strategy o-- com.stroganov.Indicators.AbstractIndicator : rsa
  com.stroganov.Strategies.AbstractRSA_Strategy o-- com.stroganov.Strategies.TradeAction : tradeAction
  com.stroganov.Strategies.RSA_Strategy o-- com.stroganov.CandleStream : candleStream
  com.stroganov.Strategies.RSA_Strategy o-- com.stroganov.Indicators.AbstractIndicator : rsa
  com.stroganov.Strategies.RSA_Strategy o-- com.stroganov.Strategies.TradeAction : tradeAction
  com.stroganov.Strategies.RSA_StrategyStopLoss -up-|> com.stroganov.Strategies.AbstractRSA_Strategy
  com.stroganov.Strategies.TradeAction o-- com.stroganov.Strategies.Balance : balance
  com.stroganov.Strategies.Transaction o-- com.stroganov.Strategies.Balance : balance


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
