@startuml

title __GRAFICS's Class Diagram__\n

  namespace com.stroganov {
    namespace Grafics {
      class com.stroganov.Grafics.GraphicOfBalance {
          {static} + drawGraphic()
      }
    }
  }
  

  namespace com.stroganov {
    namespace Grafics {
      class com.stroganov.Grafics.GraphicOfRSAIndicator {
          {static} + drawGraphic()
      }
    }
  }
  

  namespace com.stroganov {
    namespace Grafics {
      class com.stroganov.Grafics.GraphicOfTransactions {
          {static} + drawGraphic()
      }
    }
  }
  

  namespace com.stroganov {
    namespace Grafics {
      class com.stroganov.Grafics.Report {
          ~ bestTransaction : double
          ~ countBadDeal : int
          ~ countGoodDeal : int
          ~ countTransactions : int
          ~ profitPercentage : double
          ~ worseTransaction : double
          - changesAllBalance : ArrayList<Double>
          - finishBalance : double
          - startMoney : double
          - transactionArrayList : ArrayList<Transaction>
          + Report()
          {static} + compareReportByMaxBalance()
          {static} + compareReportByProfitPercentage()
          + getBestTransaction()
          + getChangesAllBalance()
          + getCountTransactions()
          + getFinishBalance()
          + getProfitPercentage()
          + getTransactionArrayList()
          + getWorseTransaction()
          + prepareReport()
          + printLn()
          + printReport()
      }
    }
  }
  

  com.stroganov.Grafics.Report o-- com.stroganov.Strategies.Balance : balance


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
